price_dir: "data/tpx500_hourly"
news_json: "data/tpx500_news_without_newsbody_contains_keywords.json"
bert_file: "data/extracted_bert.json"
correlation_table: 'data/corr_table.json,data/vol_corr_table.json'
node_num: 498
train_start: '2013-01-01'
dev_start: '2018-01-01'
test_start: '2018-05-01'
test_end: '2018-09-30'
num_layers: 1  
max_text_len: 50
max_sentence: 10
epoch: 30 
encoder: 'rnn'
graph_encoder: 'lstm'
bidirec: True
edge_threshold: 0.6    
hierarchical: False
use_text: True
use_medium: False
use_pre_emb: True
use_feature: True
freeze_emb: False
label_size: 3
vocab_size: 0
feature_size: 133
relation_num: 2
vocab_file: 'data/headline_vocab.txt'
emb_file: 'data/glove.txt'
log: 'log/'
param_init: 0.1
optim: 'adam'
learning_rate: 0.0001
max_grad_norm: 8
filter_size: 100
learning_rate_decay: 0.95 
schedule: True
start_decay_at: 2 
emb_size: 50
head_num: 4
hidden_size: 300
bert_size: 768
dropout: 0.0 

